events {
    worker_connections 1024;
}

http {
    upstream session {
        server session-service:8081;
    }

    upstream gateway {
        server gateway-service:8087;
    }

    server {
        listen 80;

        location /api/v1/auth/ {
            proxy_pass http://session/api/v1/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_request_headers on;
        }

        location /api/v1/gateway/ {
            proxy_pass http://gateway/api/v1/gateway/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_request_headers on;
        }

        location / {
            return 200 "API Gateway is running";
            add_header Content-Type text/plain;
        }
    }
}
